\newpage

# About the Author {#author .unnumbered}

**Guangchuang Yu** (https://yulab-smu.top) is a professor of bioinformatics, director of the Deparment of Bioinformatics, Southern Medical University. He earned his PhD from the School of Public Health, The University of Hong Kong. As an active R user, he has authored several R packages, such as **aplot**, **badger**, **ChIPseeker**, **clusterProfiler**, **DOSE**, **emojifont**, **enrichplot**, **ggbreak**, **ggfun**, **ggimage**, **ggplotify**, **ggtree**, **GOSemSim**, **hexSticker**, **meme**, **meshes**, **nCov2019**, **plotbb**, **ReactomePA**, **scatterpie**, **seqmagick**, **seqcombo**, **shadowtext**, **tidytree** and **treeio**. He has supervised post-graduate students to develop a few other packages, including **ggmsa**, **ggtreeExtra**, **MicrobiomeProfiler** and **MicrobiotaProcess**. 


His research group aims to generate new insights into human health and disease through the development of new software tools and novel analysis of biomedical data. The software package developed by his research group helps biologists analyze data and reveal biological clues hidden in the data. 


He has published several journal articles, including 5 highly cited papers [@yu2012; @yu_dose_2015; @yu_chipseeker:_2015; @yu_reactomepa_2016; @yu_ggtree:_2017]. The articles have been cited more than 10,000 times. The ggtree [@yu_ggtree:_2017] paper was selected as a feature article to celebrate the 10^th^ anniversary of the launch of **_Methods in Ecology and Evolution_**^[10th Anniversary Volume 8: Phylogenetic tree visualization with multivariate data: <https://methodsblog.com/2020/11/19/ggtree-tree-visualization/>]. He was one of the 2020 Highly Cited Chinese Researchers (Elsevier-Scopus) in Biomedical Engineering.


