
# Introduction {-}

```{r, eval = !knitr::is_latex_output(), echo=FALSE}
badge_version("tidytree")
badge_version("treeio")
badge_version("ggtree")
badge_version("ggtreeExtra")
```

> You can't even begin to understand biology, you can't understand life, unless
> you understand what it's all there for, how it arose - and that means
> evolution.
>
> --- Richard Dawkins


## `r if (!knitr::is_latex_output()) emoji("dart")` Motivation {-}

The book is meant as a guide for data integration, manipulation and visualization of phylogenetic trees using a suite of R packages, `r CRANpkg("tidytree")`, `r Biocpkg("treeio")` and `r Biocpkg("ggtree")`. Hence, if you are starting to read this book, we assume you have a working knowledge of how to use R and `r CRANpkg("ggplot2")`.

## `r if (!knitr::is_latex_output()) emoji("memo")` Citation {-}

If you use the software suite in published research, please cite the most appropriate paper(s) from this list:

1. __G Yu__. Using ggtree to visualize data on tree-like structures. __*Current Protocols in Bioinformatics*__, 2020, 69:e96. doi: [10.1002/cpbi.96](https://doi.org/10.1002/cpbi.96).
2. LG Wang, TTY Lam, S Xu, Z Dai, L Zhou, T Feng, P Guo, CW Dunn, BR Jones, T Bradley, H Zhu, Y Guan, Y Jiang, __G Yu__^\*^. treeio: an R package for phylogenetic tree input and output with richly annotated and associated data. __*Molecular Biology and Evolution*__. 2020, 37(2):599-603.
doi: [10.1093/molbev/msz240](http://dx.doi.org/10.1093/molbev/msz240).
3. __G Yu__^\*^, TTY Lam, H Zhu, Y Guan^\*^. Two methods for mapping and visualizing associated data on phylogeny using ggtree. __*Molecular Biology and Evolution*__. 2018, 35(2):3041-3043.
doi: [10.1093/molbev/msy194](https://doi.org/10.1093/molbev/msy194).
4. __G Yu__, DK Smith, H Zhu, Y Guan, TTY Lam^\*^. ggtree: an R package for
visualization and annotation of phylogenetic trees with their covariates and
other associated data. __*Methods in Ecology and Evolution*__. 2017, 8(1):28-36.
doi: [10.1111/2041-210X.12628](https://doi.org/10.1111/2041-210X.12628).

## `r if (!knitr::is_latex_output()) emoji("books")` Book structure {-}


+ Part 1 (Tree data input, output and manipulation) describes `r Biocpkg("treeio")` package for tree data input and output, and `r CRANpkg("tidytree")` package for tree data manipulation.
+ Part 2 (Tree data visualization and annotation) introduces tree visualization and annotation using grammar of graphic syntax implemented in the `r Biocpkg("ggtree")` package. It emphasizes on presenting tree associated data on the tree.
+ Part 3 (ggtree extensions) introduces ggtreeExtra for presenting data on circular layout trees and other extensions including MicrobiotaProcess and ggnetworx *etc.*.
+ Part 4 (Miscellaneous topics) describes utilities provided by the `r Biocpkg("ggtree")` package suite and presents a set of reproducible examples.


## `r if (!knitr::is_latex_output()) emoji("sparkling_heart")` Want to help? {-}


The book’s source code is hosted on GitHub, at <https://github.com/YuLab-SMU/treedata-book>. Any feedback on the book is very welcome. Feel free to [open an issue](https://github.com/YuLab-SMU/treedata-book/issues/new) on GitHub or send me a pull request if you notice typos or other issues (I'm not a native English speaker ;) ).

